// Empresas fictícias do modo demonstração. Nomes, gestores e IDs são 100%
// inventados — qualquer semelhança com clientes reais é coincidência a evitar
// (por isso os nomes são propositalmente genéricos/inventados).
//
// `trend` > 1 → conta melhorando no período; < 1 → piorando; ~1 → estável.
// `baseline*` são médias por dia (o gerador multiplica pelos dias do período).

export const EMPRESAS_DEMO = [
  {
    id: 'demo-aurora',
    nome: 'Aurora Cosméticos',
    identificador: 'demo-aurora-cosmeticos',
    vertical: 'e-commerce de beleza',
    prepago: false,
    bmId: '900111222',
    contaAnuncioId: 'act_100200300',
    gerenteResponsavel: 'Marina Duarte',
    investimentoMensalPlanejado: 18000,
    objetivos: [{ ordem: 1, chave: 'conversao' }],
    metasPersonalizadas: [
      { metrica: 'conversions', operador: 'acima_de', valor: 5, janela: '1d', ativo: true },
    ],
    status: 'normal',
    trend: 1.18,
    baselineSpend: 600,
    baselineCtr: 2.1,
    baselineCpm: 34,
    baselineResultadoPorDia: 6.5, // compras/dia
    roas: 4.3,
  },
  {
    id: 'demo-vertice',
    nome: 'Vértice Studio Fitness',
    identificador: 'demo-vertice-fitness',
    vertical: 'academia / personal trainer',
    prepago: false,
    bmId: '900111223',
    contaAnuncioId: 'act_100200301',
    gerenteResponsavel: 'Rafael Nogueira',
    investimentoMensalPlanejado: 6000,
    objetivos: [{ ordem: 1, chave: 'lead' }],
    metasPersonalizadas: [
      { metrica: 'leads', operador: 'acima_de', valor: 20, janela: '7d', ativo: true },
    ],
    status: 'atencao',
    trend: 1.01,
    baselineSpend: 190,
    baselineCtr: 1.4,
    baselineCpm: 28,
    baselineResultadoPorDia: 3.2, // leads/dia
  },
  {
    id: 'demo-cedro',
    nome: 'Casa Cedro Móveis',
    identificador: 'demo-casa-cedro',
    vertical: 'e-commerce de móveis e decoração',
    prepago: true,
    bmId: '900111224',
    contaAnuncioId: 'act_100200302',
    gerenteResponsavel: 'Marina Duarte',
    investimentoMensalPlanejado: 12000,
    objetivos: [{ ordem: 1, chave: 'conversao' }],
    metasPersonalizadas: [
      { metrica: 'conversions', operador: 'acima_de', valor: 8, janela: '1d', ativo: true },
    ],
    status: 'critico',
    trend: 0.81,
    baselineSpend: 400,
    baselineCtr: 1.1,
    baselineCpm: 41,
    baselineResultadoPorDia: 2.4,
    roas: 1.6,
    saldoPrepago: { nivel: 'bloqueado', saldoReais: 0, ritmoHora: 0, runwayHoras: 0, motivoBloqueio: 'Saldo insuficiente para cobrir o próximo débito' },
    entidadeComIssue: {
      motivoStatus: 'Anúncio reprovado por política de imagens de "antes e depois"',
      issues: [{ error_summary: 'Reprovado: política de práticas comerciais enganosas', error_code: 1815 }],
      status: 'DISAPPROVED',
    },
  },
  {
    id: 'demo-doce-ponto',
    nome: 'Doce Ponto Confeitaria',
    identificador: 'demo-doce-ponto',
    vertical: 'encomendas por WhatsApp',
    prepago: true,
    bmId: '900111225',
    contaAnuncioId: 'act_100200303',
    gerenteResponsavel: '',
    investimentoMensalPlanejado: 3000,
    objetivos: [{ ordem: 1, chave: 'mensagem' }],
    metasPersonalizadas: [
      { metrica: 'messaging_conversations_started', operador: 'acima_de', valor: 15, janela: '7d', ativo: true },
    ],
    status: 'normal',
    trend: 1.05,
    baselineSpend: 95,
    baselineCtr: 2.6,
    baselineCpm: 22,
    baselineResultadoPorDia: 4.1, // conversas/dia
    saldoPrepago: { nivel: 'acabando', saldoReais: 210, ritmoHora: 14, runwayHoras: 15, motivoBloqueio: null },
  },
  {
    id: 'demo-nomade',
    nome: 'Nômade Turismo & Experiências',
    identificador: 'demo-nomade-turismo',
    vertical: 'agência de viagens',
    prepago: false,
    bmId: '900111226',
    contaAnuncioId: 'act_100200304',
    gerenteResponsavel: 'Rafael Nogueira',
    investimentoMensalPlanejado: 9000,
    objetivos: [{ ordem: 1, chave: 'lead' }, { ordem: 2, chave: 'trafego' }],
    metasPersonalizadas: [
      { metrica: 'leads', operador: 'acima_de', valor: 10, janela: '7d', ativo: true },
    ],
    status: 'normal',
    trend: 0.72,
    baselineSpend: 260,
    baselineCtr: 1.7,
    baselineCpm: 30,
    baselineResultadoPorDia: 1.8, // leads/dia
  },
  {
    id: 'demo-pulso',
    nome: 'Pulso Cursos Online',
    identificador: 'demo-pulso-cursos',
    vertical: 'infoproduto',
    prepago: false,
    bmId: '900111227',
    contaAnuncioId: 'act_100200305',
    gerenteResponsavel: 'Marina Duarte',
    investimentoMensalPlanejado: null,
    objetivos: [{ ordem: 1, chave: 'conversao' }],
    metasPersonalizadas: [],
    status: 'pausado',
    trend: 1,
    baselineSpend: 0,
    baselineCtr: 1.2,
    baselineCpm: 26,
    baselineResultadoPorDia: 0,
    pausado: true,
    // Gasto residual dos ~10 dias em que a conta ainda esteve ativa antes da pausa
    // (usado só para as janelas fixas de 7d/30d — o período selecionado dá 0).
    baselineSpend7dResidual: 850,
  },
];
